import type { LockPackage } from "../src/lock/types.js";
import { indexPackages, type Lockfile } from "../src/lock/types.js";

/** Build a lockfile from a compact `name@version` list, for diff tests. */
export function lockfileOf(entries: Array<string | LockPackage>): Lockfile {
  const packages = entries.map((entry) => (typeof entry === "string" ? parseSpec(entry) : entry));

  return {
    kind: "npm",
    lockfileVersion: "3",
    packages: indexPackages(packages),
    entryCount: packages.length,
  };
}

function parseSpec(spec: string): LockPackage {
  const at = spec.indexOf("@", 1);
  return { name: spec.slice(0, at), version: spec.slice(at + 1) };
}

export const NPM_V3 = JSON.stringify({
  name: "demo",
  lockfileVersion: 3,
  requires: true,
  packages: {
    "": { name: "demo", version: "1.0.0", dependencies: { chalk: "^5.0.0" } },
    "packages/app": { name: "@demo/app", version: "0.0.0" },
    "node_modules/@demo/app": { resolved: "packages/app", link: true },
    "node_modules/chalk": {
      version: "5.3.0",
      resolved: "https://registry.npmjs.org/chalk/-/chalk-5.3.0.tgz",
      integrity: "sha512-chalk",
      license: "MIT",
    },
    "node_modules/esbuild": {
      version: "0.21.5",
      resolved: "https://registry.npmjs.org/esbuild/-/esbuild-0.21.5.tgz",
      integrity: "sha512-esbuild",
      hasInstallScript: true,
      dev: true,
      license: "MIT",
    },
    "node_modules/esbuild/node_modules/chalk": {
      version: "4.1.2",
      resolved: "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz",
      dev: true,
    },
  },
});

export const NPM_V1 = JSON.stringify({
  name: "demo",
  lockfileVersion: 1,
  dependencies: {
    chalk: {
      version: "5.3.0",
      resolved: "https://registry.npmjs.org/chalk/-/chalk-5.3.0.tgz",
      integrity: "sha512-chalk",
      dependencies: {
        "ansi-styles": { version: "6.2.1", resolved: "https://registry.npmjs.org/ansi-styles/-/x.tgz", dev: true },
      },
    },
  },
});

export const PNPM_V9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:
  .:
    dependencies:
      chalk:
        specifier: ^5.0.0
        version: 5.3.0

packages:

  '@babel/code-frame@7.24.7':
    resolution: {integrity: sha512-code-frame}

  chalk@5.3.0:
    resolution: {integrity: sha512-chalk}
    engines: {node: '>=16'}

  esbuild@0.21.5:
    resolution: {integrity: sha512-esbuild}
    hasBin: true

  request@2.88.2:
    resolution: {integrity: sha512-request}
    deprecated: request has been deprecated

  local-thing@file:../local:
    resolution: {directory: ../local, type: directory}

snapshots:

  chalk@5.3.0: {}
`;

export const PNPM_V6 = `lockfileVersion: '6.0'

packages:

  /@babel/code-frame@7.24.7:
    resolution: {integrity: sha512-code-frame}
    dev: true

  /chalk@5.3.0:
    resolution: {integrity: sha512-chalk}
    dev: false

  /esbuild@0.21.5:
    resolution: {integrity: sha512-esbuild}
    requiresBuild: true
    dev: true
`;

export const PNPM_V5 = `lockfileVersion: 5.4

packages:

  /@storybook/react/6.0.0_react@16.13.1:
    resolution: {integrity: sha512-storybook}
    dev: true

  /chalk/5.3.0:
    resolution: {integrity: sha512-chalk}
`;

export const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.10.4", "@babel/code-frame@^7.8.3":
  version "7.24.7"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.7.tgz#abc"
  integrity sha512-codeframe
  dependencies:
    "@babel/highlight" "^7.24.7"

chalk@^5.0.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-5.3.0.tgz#def"
  integrity sha512-chalk

esbuild@npm:0.21.5:
  version "0.21.5"
  resolved "https://registry.yarnpkg.com/esbuild/-/esbuild-0.21.5.tgz#ghi"
`;

export const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@babel/code-frame@npm:^7.10.4, @babel/code-frame@npm:^7.8.3":
  version: 7.24.7
  resolution: "@babel/code-frame@npm:7.24.7"
  checksum: 10c0/codeframe
  languageName: node
  linkType: hard

"chalk@npm:^5.0.0":
  version: 5.3.0
  resolution: "chalk@npm:5.3.0"
  checksum: 10c0/chalk
  languageName: node
  linkType: hard

"fsevents@patch:fsevents@npm%3A2.3.3#optional!builtin<compat/fsevents>":
  version: 2.3.3
  resolution: "fsevents@patch:fsevents@npm%3A2.3.3#optional!builtin<compat/fsevents>::version=2.3.3&hash=df0bf1"
  languageName: node
  linkType: hard

"demo@workspace:.":
  version: 0.0.0-use.local
  resolution: "demo@workspace:."
  languageName: unknown
  linkType: soft
`;
