import type { PackageChange } from "../diff.js";
import { limitOf, type RenderOptions, type Report } from "../report.js";
import type { Signal, SignalLevel } from "../signals.js";
import { formatBytesDelta, plural, printable } from "./format.js";

/**
 * Marker so a workflow can find and update its previous comment instead of
 * posting a new one on every push.
 */
export const COMMENT_MARKER = "<!-- lockreview -->";

const LEVEL_MARK: Record<SignalLevel, string> = { high: "🔴", warn: "🟡", info: "⚪" };

/** Render the report as GitHub-flavoured markdown, sized for a PR comment. */
export function renderMarkdown(report: Report, options: RenderOptions): string {
  const blocks: string[] = [COMMENT_MARKER, `### lockreview — ${code(report.lockfile)}`];

  blocks.push(headline(report));

  if (report.summary.signals.length > 0) blocks.push(signalsTable(report.summary.signals, options));
  if (report.diff.changed.length > 0) blocks.push(changedTable(report.diff.changed, options));
  if (report.diff.added.length > 0) blocks.push(listSection("Added", report.diff.added, options));
  if (report.diff.removed.length > 0) {
    blocks.push(listSection("Removed", report.diff.removed, options));
  }

  if (report.notes.length > 0) {
    blocks.push(report.notes.map((note) => `<sub>${text(note)}</sub>`).join("<br>"));
  }

  blocks.push(
    `<sub>Comparing ${code(report.before.label)} → ${code(report.after.label)}. Generated by [lockreview](https://github.com/vineetdev02/lockreview).</sub>`,
  );

  return `${blocks.join("\n\n")}\n`;
}

function headline(report: Report): string {
  const { summary } = report;

  if (summary.added + summary.removed + summary.changed === 0) {
    return "No dependency changes.";
  }

  const counts = [
    summary.added > 0 ? `**${summary.added} added**` : "",
    summary.removed > 0 ? `**${summary.removed} removed**` : "",
    summary.changed > 0 ? `**${summary.changed} changed**` : "",
  ].filter(Boolean);

  const extras = [
    summary.major > 0 ? `${summary.major} major` : "",
    summary.downgrades > 0 ? `${summary.downgrades} downgraded` : "",
    summary.size
      ? `install size ${formatBytesDelta(summary.size.bytes)}${
          summary.size.platformSpecific > 0
            ? ` (${plural(summary.size.platformSpecific, "platform-specific package")} not counted)`
            : ""
        }`
      : "",
    `${summary.entriesBefore} → ${summary.entriesAfter} installed packages`,
  ].filter(Boolean);

  return `${counts.join(" · ")}\n\n${extras.join(" · ")}`;
}

function signalsTable(signals: Signal[], options: RenderOptions): string {
  const limit = limitOf(options);
  const shown = signals.slice(0, limit);

  const rows = shown.map((signal) => {
    const detail = signal.detail ? `<br><sub>${text(signal.detail)}</sub>` : "";
    return `| ${LEVEL_MARK[signal.level]} | ${code(signal.package, true)} | ${text(signal.title)}${detail} |`;
  });

  if (signals.length > shown.length) {
    rows.push(`| | | …and ${signals.length - shown.length} more |`);
  }

  return ["#### Worth a look", "", "| | Package | Finding |", "| :-: | --- | --- |", ...rows].join(
    "\n",
  );
}

function changedTable(changes: PackageChange[], options: RenderOptions): string {
  const limit = limitOf(options);
  const shown = changes.slice(0, limit);

  const rows = shown.map((change) => {
    const bump = change.bump && change.bump !== "other" ? change.bump : "";
    const marker = change.breaking ? `**${bump}**` : bump;
    return `| ${marker} | ${code(change.name, true)} | ${code(change.from ?? "?", true)} → ${code(change.to ?? "?", true)} |`;
  });

  if (changes.length > shown.length) {
    rows.push(`| | …and ${changes.length - shown.length} more | |`);
  }

  return details(
    plural(changes.length, "package") + " changed",
    ["| Update | Package | Version |", "| --- | --- | --- |", ...rows].join("\n"),
  );
}

function listSection(title: string, changes: PackageChange[], options: RenderOptions): string {
  const limit = limitOf(options);
  const shown = changes.slice(0, limit);

  const entries = shown.map((change) => {
    const version = change.kind === "removed" ? change.from : change.to;
    return code(`${change.name}@${version ?? "?"}`);
  });

  if (changes.length > shown.length) {
    entries.push(`…and ${changes.length - shown.length} more`);
  }

  return details(`${title}: ${plural(changes.length, "package")}`, entries.join(", "));
}

function details(summary: string, body: string): string {
  return `<details>\n<summary>${text(summary)}</summary>\n\n${body}\n\n</details>`;
}

/**
 * Text from somewhere else, made inert in a comment.
 *
 * A deprecation notice is written by the package's author and lands in every
 * downstream pull request this runs on, under the bot's name. Unescaped, it
 * can be a link whose text says "security update" and whose target says
 * anything, an image that loads for every reviewer, a mention that notifies
 * strangers, or an issue reference that points into the repository it is
 * posted in. So markdown's punctuation is escaped, HTML and entities are
 * spelled out, and `@name` and `#123` get a zero-width space after the sigil:
 * still readable, no longer live. `|` is escaped too, which is what keeps a
 * table cell a cell.
 */
function text(value: string): string {
  return printable(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/[\\`*_[\]~|]/g, "\\$&")
    // `#` before `@`: the entity the `@` rule inserts contains `#8`, which the
    // `#` rule would otherwise split into visible garbage. A mention only
    // starts where a word does, so `checkout@v4`, `pkg@1.0.0` and an email
    // address are left as they are.
    .replace(/#(?=\d)/g, "#&#8203;")
    .replace(/(?<![\w`])@(?=[\w-])/g, "@&#8203;");
}

/**
 * A code span that cannot be broken out of. The fence is one backtick longer
 * than any run inside, so a backtick in a name stays part of the name — a
 * lockfile in a pull request is written by whoever opened it. Inside a table
 * a `|` still ends the cell, code span or not, so it is escaped there; outside
 * one the escape would print.
 */
function code(value: string, inTable = false): string {
  const content = printable(value);
  const longest = Math.max(0, ...[...content.matchAll(/`+/g)].map((run) => run[0].length));
  const fence = "`".repeat(longest + 1);
  const padded = content.startsWith("`") || content.endsWith("`") ? ` ${content} ` : content;
  return `${fence}${inTable ? padded.replace(/\|/g, "\\|") : padded}${fence}`;
}
