import type { PackageChange } from "../diff.js";
import { limitOf, type RenderOptions, type Report } from "../report.js";
import type { Signal, SignalLevel } from "../signals.js";
import { formatBytesDelta, plural } from "./format.js";

/**
 * Marker so a workflow can find and update its previous comment instead of
 * posting a new one on every push.
 */
export const COMMENT_MARKER = "<!-- lockreview -->";

const LEVEL_MARK: Record<SignalLevel, string> = { high: "🔴", warn: "🟡", info: "⚪" };

/** Render the report as GitHub-flavoured markdown, sized for a PR comment. */
export function renderMarkdown(report: Report, options: RenderOptions): string {
  const blocks: string[] = [COMMENT_MARKER, `### lockreview — \`${report.lockfile}\``];

  blocks.push(headline(report));

  if (report.summary.signals.length > 0) blocks.push(signalsTable(report.summary.signals, options));
  if (report.diff.changed.length > 0) blocks.push(changedTable(report.diff.changed, options));
  if (report.diff.added.length > 0) blocks.push(listSection("Added", report.diff.added, options));
  if (report.diff.removed.length > 0) {
    blocks.push(listSection("Removed", report.diff.removed, options));
  }

  if (report.notes.length > 0) {
    blocks.push(report.notes.map((note) => `<sub>${escapeText(note)}</sub>`).join("<br>"));
  }

  blocks.push(
    `<sub>Comparing \`${escapeText(report.before.label)}\` → \`${escapeText(report.after.label)}\`. Generated by [lockreview](https://github.com/vineetdev02/lockreview).</sub>`,
  );

  return `${blocks.join("\n\n")}\n`;
}

function headline(report: Report): string {
  const { summary } = report;

  if (summary.added + summary.removed + summary.changed === 0) {
    return "No dependency changes.";
  }

  const counts = [
    summary.added > 0 ? `**${summary.added} added**` : "",
    summary.removed > 0 ? `**${summary.removed} removed**` : "",
    summary.changed > 0 ? `**${summary.changed} changed**` : "",
  ].filter(Boolean);

  const extras = [
    summary.major > 0 ? `${summary.major} major` : "",
    summary.downgrades > 0 ? `${summary.downgrades} downgraded` : "",
    summary.size ? `install size ${formatBytesDelta(summary.size.bytes)}` : "",
    `${summary.entriesBefore} → ${summary.entriesAfter} installed packages`,
  ].filter(Boolean);

  return `${counts.join(" · ")}\n\n${extras.join(" · ")}`;
}

function signalsTable(signals: Signal[], options: RenderOptions): string {
  const limit = limitOf(options);
  const shown = signals.slice(0, limit);

  const rows = shown.map((signal) => {
    const detail = signal.detail ? `<br><sub>${escapeText(signal.detail)}</sub>` : "";
    return `| ${LEVEL_MARK[signal.level]} | \`${escapeText(signal.package)}\` | ${escapeText(signal.title)}${detail} |`;
  });

  if (signals.length > shown.length) {
    rows.push(`| | | …and ${signals.length - shown.length} more |`);
  }

  return ["#### Worth a look", "", "| | Package | Finding |", "| :-: | --- | --- |", ...rows].join(
    "\n",
  );
}

function changedTable(changes: PackageChange[], options: RenderOptions): string {
  const limit = limitOf(options);
  const shown = changes.slice(0, limit);

  const rows = shown.map((change) => {
    const bump = change.bump && change.bump !== "other" ? change.bump : "";
    const marker = change.breaking ? `**${bump}**` : bump;
    return `| ${marker} | \`${escapeText(change.name)}\` | \`${change.from ?? "?"}\` → \`${change.to ?? "?"}\` |`;
  });

  if (changes.length > shown.length) {
    rows.push(`| | …and ${changes.length - shown.length} more | |`);
  }

  return details(
    plural(changes.length, "package") + " changed",
    ["| Update | Package | Version |", "| --- | --- | --- |", ...rows].join("\n"),
  );
}

function listSection(title: string, changes: PackageChange[], options: RenderOptions): string {
  const limit = limitOf(options);
  const shown = changes.slice(0, limit);

  const entries = shown.map((change) => {
    const version = change.kind === "removed" ? change.from : change.to;
    return `\`${escapeText(change.name)}@${version ?? "?"}\``;
  });

  if (changes.length > shown.length) {
    entries.push(`…and ${changes.length - shown.length} more`);
  }

  return details(`${title}: ${plural(changes.length, "package")}`, entries.join(", "));
}

function details(summary: string, body: string): string {
  return `<details>\n<summary>${escapeText(summary)}</summary>\n\n${body}\n\n</details>`;
}

/** Keep table cells and inline code from breaking the surrounding markdown. */
function escapeText(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/</g, "&lt;").replace(/\r?\n/g, " ");
}
